title: Website Detachment 085 AFROTC
description: Website for the Detachment 085 AFROTC
theme: just-the-docs

url: https://Berkeley085.github.io/my-docs-site

  # aux_links:
  #   Template Repository: https://github.com/just-the-docs/just-the-docs-template
